name: jupyterlab-environment
channels:
- conda-forge
dependencies:
# Jupyter
# - jupyterlab=3
# - jupyter-offlinenotebook=0.2
- nodejs=12
- nbconvert=6
# Python Kernel
- ipykernel=5.1
- xeus-python=0.9
- ipywidgets=7.6
- widgetsnbextension=3.5
- ipyleaflet=0.13
- altair=4.1
- bqplot=0.12.20
- dask=2020.12
- matplotlib=3.1
# - japanize_matplotlib=1.1.3
- pandas=1
- plotly=4.14.3
- python=3.8
- scikit-image=0.15
- scikit-learn=0.21
- seaborn=0.11
- tensorflow=1.13
- sympy=1.4
- pyyaml
- traittypes==0.2.1
- invoke=1.2
